### ISSUE TITLE
Update to support Angular 16?

### ISSUE THREAD

**Issue by FabianGosebrink** [udos86/ng-dynamic-forms#1173]
## I'm submitting a
<pre><code>
[x] Feature Request / Proposal
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `17.0.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Is it planned to move this lib to support Angular 16?

**Comment by udos86** [comment]
@FabianGosebrink 

I promise to release a new version supporting Angular 16 as soon as possible

**Comment by nick-goloborodko** [comment]
Just about to start a new project and would love to use ng-dynamic-forms over ngx-formly (as formly is pretty limited with primeng and just doesn't feel right for some reason). The project is based on angular 16, so obviously can't quite use the current version of the library from NPM due to dependencies.

**Comment by udos86** [comment]
@nick-goloborodko 

I've just released `18.0.0` with support for Angular 16.
