### ISSUE TITLE
AOT Compilation with Angular CLI

### ISSUE THREAD

**Issue by timmyrosen** [udos86/ng-dynamic-forms#514]
## I'm submitting a...
<pre><code>
[x] Bug
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using...
<pre><code>
NG Dynamic Forms Version: 1.4.31

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Hi!
Awesome plugin for starters!

I'm experiencing a problem when compiling with aot flag in Angular CLI (v 1.4.1) (compiler-cli v 4.2.4). The problem does not appear when using --aot=false

When trying to add a DynamicInputModel to a DynamicFormGroupModel I get the following error in console:

```
ERROR TypeError: t.splice is not a function
    at 3.37cf5c36cf41307ab3e1.chunk.js:1
    at Array.forEach (<anonymous>)
    at e.insertFormGroupControl (3.37cf5c36cf41307ab3e1.chunk.js:1)
    at e.addFormGroupControl (3.37cf5c36cf41307ab3e1.chunk.js:1)
    at e.dropInput (3.37cf5c36cf41307ab3e1.chunk.js:1)
    at Object.handleEvent (3.37cf5c36cf41307ab3e1.chunk.js:1)
    at Object._ [as handleEvent] (vendor.fcadd8823737b1670225.bundle.js:1)
    at Object.handleEvent (vendor.fcadd8823737b1670225.bundle.js:1)
    at oe (vendor.fcadd8823737b1670225.bundle.js:1)
    at vendor.fcadd8823737b1670225.bundle.js:1
```

As I said, it works perfectly locally and when --aot=false so I don't think there is anything wrong with my code.

Thanks!

**Comment by udos86** [comment]
@timmyrosen Hi!

> Awesome plugin for starters!

Thank you very much!

> As I said, it works perfectly locally and when --aot=false so I don't think there is anything wrong with my code.

I can confirm, this is a bug indeed. I'll deliver a patch as soon as possible.

Thanks for reporting this.

**Comment by udos86** [comment]
@timmyrosen 

After some further investigation I was able to locate the origin of this bug. 

Angular CLI just breaks the `instanceof` operator. 

This is the original library source code:
```
if (groupModel instanceof DynamicFormGroupModel) {
  groupModel.insert(index, controlModel);

} else {
  (groupModel as DynamicFormControlModel[]).splice(index, 0, controlModel);
}
```

That's the output of Angular CLI `ng build --aot`:
```
if (groupModel instanceof __WEBPACK_IMPORTED_MODULE_2__model_form_group_dynamic_form_group_model__["b" /* DynamicFormGroupModel */]) {
  groupModel.insert(index, controlModel);
}
else {
  groupModel.splice(index, 0, controlModel);
}
```

I'll file a bug.

**Comment by timmyrosen** [comment]
I see, thanks for quick reply!

So this is in the hands of the Angular CLI team now?

**Comment by udos86** [comment]
@timmyrosen Yep! 

https://github.com/angular/angular-cli/issues/7788.

**Comment by about-code** [comment]
@udos86 Are you sure its a CLI-problem? I don't think the replacement with the webpack variable itself does break the instanceof operator given that `__WEBPACK_IMPORTED_MODULE_2__model_form_group_dynamic_form_group_model__["b"]` correctly references the correct constructor function. If it wouldn't it would be a severe webpack problem causing many other projects to fail. I don't think that's the case here.

E.g. you may want to try the following snippet in Chrome:

```
class Foo {
    constructor() {}
}

class Bar {
    constructor() {}
}

__WEBPACK_IMPORTED_MODULE_2__model_form_group_dynamic_form_group_model__ = {
 "b": Foo,
 "c": Bar   
};

var foo = new Foo();

console.log(foo instanceof __WEBPACK_IMPORTED_MODULE_2__model_form_group_dynamic_form_group_model__["b" /* DynamicFormGroupModel */]);
console.log(foo instanceof __WEBPACK_IMPORTED_MODULE_2__model_form_group_dynamic_form_group_model__["c" /* DynamicFormGroupModel */]);

// Output:
// true
// false
```

I think the problem is that in your code-samples there's the assumption that `groupModel` is always an array if it is not an atomic instance. But if its `null`, for example, then its neither an instance of FGM nor an array.

**Comment by udos86** [comment]
@about-code Hi there, old coding friend! Thanks for your contribution to this issue!

> If it didn't it were a severe webpack problem causing many other projects to fail. I don't think that's the case here.

I'm aware that this highly unlikely the case, but here's a screenshot to beat the odds:

<img width="1424" alt="bildschirmfoto 2017-09-24 um 13 13 21" src="https://user-images.githubusercontent.com/508325/30782069-cf318c54-a12a-11e7-9632-7040ed54c793.png">

As you can see `groupModel` is indeed a `DynamicFormGroupModel`. 

Yet the `instanceof` check gives `false` as a result.

> I think the problem is that in your code-samples there's the assumption that groupModel is always an array if it is not an atomic instance. But if its null, for example, or an atomic instance of a completely different class, then its neither an instance of DynamicFormControlModel nor DynamicFormControlModel[].

In the abstract you're right. But due to the parameter typing this case is forbidden:

>     insertFormGroupControl(index: number,
>                            formGroup: FormGroup,
>                            **groupModel: DynamicFormControlModel[] | DynamicFormGroupModel,**
>                            ...controlModels: DynamicFormControlModel[]):

**Comment by about-code** [comment]
In the console output it looks as if `__WEBPACK...` variable holds a reference on a `DynamicFormGroupModel` constructor and `groupModel` is an instance of DynamicFormGroupModel. So the instanceof check should indeed return `true`.

What happens if you compare 
```
groupModel.constructor === __WEBPACK_IMPORTED_MODULE_2__model_form_group_dynamic_form_group_model__["b"]
```

If the result is `false` it is a sign that there likely exist two different definitions of `DynamicFormGroupModel` constructor function in the bundles for whatever reason. In your screenshot on the left there are multiple bundles loaded. May it be that webpack put another definition of the class in one of the other bundles?

Is there another webpack config apart from `webpack.config.js`? You don't use [CommonsChunkPlugin](https://webpack.js.org/guides/code-splitting/#prevent-duplication) there.

**Comment by udos86** [comment]
@about-code 

> If the result is false it is a sign that there likely exist two different definitions of DynamicFormGroupModel constructor function in the bundles for whatever reason.

Yep, that's exactly my assumption according to this console output:

```
groupModel.constructor === __WEBPACK_IMPORTED_MODULE_2__model_form_group_dynamic_form_group_model__["b"]
false
```

```
groupModel.constructor.name === __WEBPACK_IMPORTED_MODULE_2__model_form_group_dynamic_form_group_model__["b"].name
true
```

> Is there another webpack config apart from webpack.config.js? You don't use CommonsChunkPlugin there.

No, Angular CLI is hiding away Webpack entirely from the developer. There's no way of manipulating it's configuration. That's why my hands are tied here.

**Comment by udos86** [comment]
@about-code 

Alright, here is ultimate evidence, what's going on.

This is the line of  code that creates the `groupModel` instance:
`new __WEBPACK_IMPORTED_MODULE_0__ng_dynamic_forms_core__["k" /* DynamicFormGroupModel */]({...})`

And that's the line of code that uses `instanceof`:
```
if (groupModel instanceof __WEBPACK_IMPORTED_MODULE_2__model_form_group_dynamic_form_group_model__["b" /* DynamicFormGroupModel */]) {
  groupModel.insert(index, controlModel);
}
```
It's obvious...

**Comment by about-code** [comment]
@udos86 Have seen the thread over at angular-cli. If you want to give [ng-packagr](https://github.com/dherges/ng-packagr) a try you might also find a [script](https://github.com/about-code/slush-ng-monorepo-sample/blob/master/scripts/build-packages.js) in my repo helpful. It iterates over your packages folder and builds every package with an `ng-package.json`. 

You might need to adjust the relative path in the script pointing to '../packages', depending on where you put the script in your repo. If you have any third-party deps you need to add them to the externals section of the respective package's ng-package.json. Then run the script as a node script (requires `ng-packagr` and `rimraf`).

**Comment by udos86** [comment]
@about-code 

You know, I really like your work and I'll follow your progress on your new project.

And I also like ng-packagr - it's a really nice tool. But with this project I wanted to succeed on my own. So after more spending multiple hours tonight on this I finally got it going.

From the next release on NG Dynamic Forms will meet Angular Package Format requirements which ultimately resolves this issue here.

Maybe you'd like to have a look at https://github.com/udos86/ng-dynamic-forms/commit/5e53e6436021f5d20ca4cb14f6ed15000721db48

What's really imported is that your `tsconfig.json` for `ngc` is properly configured as well as your `package.json`.

This took me a while to get my head around.

Thank @timmyrosen for bringing this up and @about-code for your expertise.

**Comment by timmyrosen** [comment]
Wow, great work! Will test tomorrow, glad I could help!

**Comment by about-code** [comment]
> You know, I really like your work and I'm following your progress on your new project, of course.

So do I.

> But with this project I wanted to succeed on my own

I like that attitude. Good to know where I can ask for advice should I have to find out the hard way, that my lazyness hasn't teached me the lessons you've just learned.
