### ISSUE TITLE
Autocomplete behaviour on demo site

### ISSUE THREAD

**Issue by hakalb** [udos86/ng-dynamic-forms#679]
## I'm submitting a

<pre><code>
[] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: Demo site

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
I want to implement autocomplete so I checked the demo site for material.
http://ng2-dynamic-forms.udos86.de/sample/index.aot.html#/material-sample-form

I am not sure how it is suppose to work in dynamic forms but the example State using autocomplete doesn't behave as I expect it to do.
When I type I want the list to be filtered so it helps me finding the text I am typing. Right now it is more like a simple drop down.

Am I missing something or is the demo broken?

Regards Håkan

**Comment by udos86** [comment]
@hakalb Hi Håkan!

Currently this is the expected behavior as documented on [Material site](https://material.angular.io/components/autocomplete/overview#simple-autocomplete). 

However you implement a custom filter by tracking the value changes of a control and the updating the `list` property of your corresponding model.

**Comment by m98** [comment]
Thanks for this impressive library.

But this is not the expected behavior which most users need. Is there any implemented method of searching the Material autocomplete?
