### ISSUE TITLE
NG Bootstrap: Auto complete is missing on textarea

### ISSUE THREAD

**Issue by wnabil** [udos86/ng-dynamic-forms#752]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.2`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Auto complete is missing on textarea

**Comment by udos86** [comment]
@wnabil Hi!

Thanks for your feature request and contribution.

Unfortunately I have to decline this as `<textarea>` simply [**does not support**](https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/compiler/src/schema/dom_element_schema_registry.ts) `autocomplete` at the moment.

That's why the Travis build is breaking with your changes as the unit tests are not passing any more:

`Can't bind to 'autocomplete' since it isn't a known property of 'textarea'.`
