### ISSUE TITLE
Bootstrap 4 feature request

### ISSUE THREAD

**Issue by kamekazemaster** [udos86/ng-dynamic-forms#780]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[X] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.0.5`

[ ] Basic UI
[X] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[X] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description

Since Bootstrap 4 is stable for a while now it would be great if this library also supports the new version of Bootstrap.

I tried to implement a Radio Group with "Bootstrap UI" using the new grid system of bootstrap based on flexbox. I wanted that each 2 options of the Radio Group are in one line (col-6 for each single option). Apparently, here the problem is that in the generated template the options of a Radio Group are wrapped in a `<fieldset>` tag and there are certain limitations when it comes to flexbox and `<fieldset>` ([https://github.com/twbs/bootstrap/issues/21666](https://github.com/twbs/bootstrap/issues/21666)).

Certainly there are more changes to make to be bootstrap 4 conform wrapped up in the migration guide of Bootstrap 4 ([https://getbootstrap.com/docs/4.1/migration/](https://getbootstrap.com/docs/4.1/migration/)).

Thank you for this great library! I would love to use it in our projects but since we updated all our projects to Bootstrap 4 already it is just not possible at the moment.

**Comment by udos86** [comment]
@kamekazemaster Hi!

> Thank you for this great library! I would love to use it in our projects but since we updated all our projects to Bootstrap 4 already it is just not possible at the moment.

Thank you very much for the kind words!

Bootstrap 4 is already supported! Just switch to the NG Bootstrap UI package!

**Comment by danimt** [comment]
@udos86 Using NG Bootstrap UI package is not the solution, just a workaround. 

The issue here, for example as encountered by me, is that I cannot have a `DynamicFormGroupModel` (which is a `fieldset` in UI Bootstrap) use the row/form-row classes because of this https://github.com/twbs/bootstrap/issues/21666, and it seems we don't have any way of adjusting this. 

Only changing to NG Bootstrap UI, which doesn't use `<fieldset>` for groups, but a `<div>`, it works, but adds a ton of unwanted code I am not looking for, as I just want the CSS/HTML structure of Bootstrap.
