### ISSUE TITLE
Additional Property for DynamicFormArrayModelConfig

### ISSUE THREAD

**Issue by neil-coutinho** [udos86/ng-dynamic-forms#859]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[x ] Feature Request / Proposal
[x ] Question
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `6.2.0`

[ ] Basic UI
[x ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[x ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
DynamicFormArrayModelConfig [here](http://ng2-dynamic-forms.udos86.de/docs/core/interfaces/_model_form_array_dynamic_form_array_model_.dynamicformarraymodelconfig.html) does not seem to have an **additional** property like DynamicInputControlModelConfig [here](http://ng2-dynamic-forms.udos86.de/docs/core/interfaces/_model_dynamic_input_control_model_.dynamicinputcontrolmodelconfig.html)

@udos86 Is it possible to add additional custom configuration for ArrayModel?
I am trying to add a min / max config to by Arrray fields

**Comment by stekontar** [comment]
@udos86  any news on this?
I believe that is better to add it on dynamicFormControlMolelConfig as both 
DynamicFormArrayModelConfig and DynamicFormGroupModelConfig extends it.
In this way both group and array could support additional.

Regards,
S.

**Comment by udos86** [comment]
`additional` is reserved only for properties specific to a certain control type of a certain UI library.

**Comment by stekontar** [comment]
Dear @udos86 

I know that is almost a year which this issue has been opened but I am still struggling to find a workaround in order to pass custom attributes in formGroup/formArray 

As @neil-coutinho mention min/max attribute on Array or some custom property on Group 
I believe is needed it in order to support custom functionality
(e.g change Control behavior or change group/array style or enable or disable group/array), 

Control already supports this functionality for specific properties but also could support any other desired property based on developers needs.

I believe that the only change would be to move additional property 
from DynamicFormValueControlModelConfig 
to DynamicFormControlModelConfig

and 

@serializable() additional: { [key: string]: any } | null;

getAdditional(key: string, defaultValue: any | null | undefined = undefined): any {
 return this.additional !== null && this.additional.hasOwnProperty(key) ? this.additional[key] : 
           defaultValue;
}

from DynamicFormValueControlModel
to DynamicFormControlModel

as every other configuration extends it.

Regards,
S.
