### ISSUE TITLE
Display validation messages on form submit

### ISSUE THREAD

**Issue by PixelVibe** [udos86/ng-dynamic-forms#987]
## I'm submitting a

<pre><code>
[x] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `X.Y.Z`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[x] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
On form submit the error messages do not show. It works as expected when the user interacts with the fields and validation messages show.
I couldn't find a complete example with a form having an actual submit button to check if I am doing something wrong, or maybe for this scenario I have to make use of the dynamic-material-form-control
approach!

Using the provided basic code example 
https://stackblitz.com/edit/angular-vqmwb3

thank you

**Comment by udos86** [comment]
@PixelVibe Hi! 

There's no bug in here. 

> On form submit the error messages do not show. 

It's just the default behavior of Angular. As this is a custom UX requirement it is solely up to you to implement that kind of mechanism. Others would prefer to disable the submit button when the corresponding form is invalid.

For controlling error messages in Material please also have look at the official docs: https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown

**Comment by PixelVibe** [comment]
@udos86 Hello and thank you. I am really sorry for the misunderstanding, as I wanted to point out the angular material field indication (usually red color) when you try to submit a form that has a form control with a validator which is invalid and not displaying the actual error message.

I have updated the example with an input field which has a required validator to demonstrate the difference and the potential bug I suppose?
https://stackblitz.com/edit/angular-zaxu21

**Comment by udos86** [comment]
@PixelVibe 

Alright, thanks for clearing that up. I'll have a look at this.

**Comment by PixelVibe** [comment]
@udos86 Thank you.
In case someone else faces the same problem regardless if it is a bug or by design, a solution like `this.formGroup.markAllAsTouched()` does the trick with added bonus the error message.

**Comment by udos86** [comment]
@PixelVibe 

Thanks, that would be a valid workaround.

After some investigation I do remember it all again ;-) 

This is actually no bug here but a consequence of how `FormGroupDirective` is implemented. Angular does not allow `formGroupName` to be bound in a nested component without having a `[formGroup]` at the same time in the template. So an independent form group context is automatically created due to the necessary form group directive that has no linking to the parent `FormGroupDirective` and does not inherit the `submitted` property which the Material error state matcher checks. 

To me this has always been a true design weakness in Reactive Forms.

For more details see the official issue: https://github.com/angular/angular/issues/21263#issuecomment-472440261
